### ISSUE TITLE
Running the plug-in with the external ruleset file results in a `NoSuchMethodError`

### ISSUE THREAD

**Issue by 0x6675636b796f75676974687562** [nbadal/ktlint-intellij-plugin#293]
Running the plug-in with the external ruleset file ([`diktat.jar`](https://github.com/saveourtool/diktat)) results in a `NoSuchMethodError`

```
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.psi.KtPsiFactory.<init>(org.jetbrains.kotlin.com.intellij.openapi.project.Project, boolean)'
	at org.cqfn.diktat.ruleset.rules.chapter2.comments.CommentsRule.logic(CommentsRule.kt:37)
	at org.cqfn.diktat.ruleset.rules.DiktatRule.visit(DiktatRule.kt:63)
	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:148)
	at com.pinterest.ktlint.core.KtLint$lint$1.invoke(KtLint.kt:141)
	at com.pinterest.ktlint.core.internal.VisitorProvider$concurrentVisitor$1$1.invoke(VisitorProvider.kt:102)
	at com.pinterest.ktlint.core.internal.VisitorProvider$concurrentVisitor$1$1.invoke(VisitorProvider.kt:96)
	at com.pinterest.ktlint.core.ast.PackageKt.visit(package.kt:236)
	at com.pinterest.ktlint.core.internal.VisitorProvider$concurrentVisitor$1.invoke(VisitorProvider.kt:96)
	at com.pinterest.ktlint.core.internal.VisitorProvider$concurrentVisitor$1.invoke(VisitorProvider.kt:95)
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:141)
	at com.nbadal.ktlint.KtLintWrapper.lint(KtLintWrapper.kt:10)
	at com.nbadal.ktlint.KtlintProcessingKt.doLint(KtlintProcessing.kt:99)
	at com.nbadal.ktlint.KtlintAnnotator.collectInformation(KtlintAnnotator.kt:21)
	at com.nbadal.ktlint.KtlintAnnotator.collectInformation(KtlintAnnotator.kt:14)
	at com.intellij.lang.annotation.ExternalAnnotator.collectInformation(ExternalAnnotator.java:60)
```

Apparently, the ruleset JAR depends on a different _KtLint_ version (**0.46.1**) than the one shipped with the plug-in, and binary compatibility is not preserved.

So maybe it makes sense to ship multiple different _KtLint_ versions, letting the user choose which version to run. For instance, [Checkstyle plug-in](https://github.com/jshiell/checkstyle-idea) for IDEA offers exactly that.

**Comment by paul-dingemans** [comment]
Ktlint has been heavily refactored in last 2 years. As a result there were many breaking changes in the API resulting in problems like this. Now that Ktlint 1.0 has been released, the API is to be expected to be more stable and the problem should not occur provided that the ruleset has implemented the `RuleSetProviderV3` interface.
